### ISSUE TITLE
mixing with unlabeled datasets

### ISSUE THREAD

**Issue by NoName5990** [kumuji/mix3d#25]
Hi, @kumuji 
Thank you for your excellent work! How to mix labeled and unlabeled data? I want to know if it is right or not when I want to mix labeled data and unlabeled data. I first moved them to the origin and concatenated their coordinates directly, then I changed one data label to -1 as unlabeled data and concatenated the labels of the two data. I mainly want to know if the operation of the label is correct and consistent with what you mentioned in your paper.

**Comment by kumuji** [comment]
Hi @NoName5990 ,

I think you got it right, the only difference is the ignore label. In my code I used `255` instead of `-1` as the value for `ignore_label`, but it should not change the result.
In my experiments, I changed the labels for one of the point clouds to an `ignore_label` before merging the point clouds as usual.

Please check the code that follows the line: https://github.com/kumuji/mix3d/blob/9015e138cf64ece5aa392be173b8fb9d5afe9573/mix3d/datasets/utils.py#L97 .
You will notice that I replace the labels for the second point cloud with an `ignore_label`: https://github.com/kumuji/mix3d/blob/9015e138cf64ece5aa392be173b8fb9d5afe9573/mix3d/datasets/utils.py#L108 .

Hope that helps!

**Comment by NoName5990** [comment]
Thank you for your explanation, I got it now.
